# Generated by Django 3.1.4 on 2021-03-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_storage_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='coordinates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
